"""Turns a company's raw numbers into the words a rep actually uses: a one-line
"why they're worth a call", the score broken into its parts, and a talking point
per exposed surface. Nothing here is generated by a model — it's the taxonomy's
own copy stitched onto the company's evidence, so it stays honest and fast."""

from __future__ import annotations

import math

from .db import Database
from .schemas.company import ScoreFactor, SignalHit


def _join(labels: list[str]) -> str:
    labels = [label.lower() for label in labels]
    if not labels:
        return "no notable surface"
    if len(labels) == 1:
        return labels[0]
    if len(labels) == 2:
        return f"{labels[0]} and {labels[1]}"
    return ", ".join(labels[:-1]) + f", and {labels[-1]}"


def score_breakdown(
    db: Database, mask: int, hostname_count: int, net24_count: int
) -> list[ScoreFactor]:
    meta = db.meta()
    sw = float(meta["score_signal_weight"])
    zw = float(meta["score_size_weight"])
    pw = float(meta["score_spread_weight"])
    size_cap = float(meta["score_size_cap"])
    spread_cap = float(meta["score_spread_cap"])
    total = float(meta["total_signal_weight"])

    keys = db.keys_in_mask(mask)
    weight_sum = sum(db.signal_by_key[k].weight for k in keys)
    signal_c = weight_sum / total if total else 0
    size_c = min(1.0, math.log(1 + hostname_count) / math.log(1 + size_cap))
    spread_c = min(1.0, math.log(1 + net24_count) / math.log(1 + spread_cap))

    return [
        ScoreFactor(
            label="Exposed signals",
            detail=f"{len(keys)} of {len(db.signals)} categories, risk-weighted",
            contribution=round(100 * sw * signal_c, 1),
        ),
        ScoreFactor(
            label="Hostname footprint",
            detail=f"{hostname_count:,} public hostnames",
            contribution=round(100 * zw * size_c, 1),
        ),
        ScoreFactor(
            label="Network spread",
            detail=f"{net24_count:,} distinct /24 networks",
            contribution=round(100 * pw * spread_c, 1),
        ),
    ]


def summary(domain: str, country: str, hostname_count: int, net24_count: int,
            hits: list[SignalHit]) -> str:
    where = f" in {country}" if country and country != "Global" else ""
    surface = _join([h.label for h in hits])
    networks = "network" if net24_count == 1 else "networks"
    return (
        f"{domain} exposes {hostname_count:,} public hostnames across "
        f"{net24_count:,} {networks}{where}, surfacing {surface}."
    )


def talking_points(hits: list[SignalHit]) -> list[str]:
    points = []
    for h in hits:
        example = f" (e.g. {h.example_hostname})" if h.example_hostname else ""
        points.append(f"{h.label}{example} — {h.talking_point}")
    return points
